name: Sync labels

on:
  push:
    branches: ["main"]
    paths:
      - ".github/labels.yml"
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync labels from .github/labels.yml
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: true


